---
  - name: Adding gpg key to Docker
    apt_key: keyserver=hkp://pgp.mit.edu:80 id=58118E89F3A912897C070ADBF76221572C52609D

  - name: Adding repository for Docker
    apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main'

  - name: Update packages
    apt: update_cache=yes

  - name: Install docker.
    apt: name=docker-engine state=present


